version: '3'
services:
  nginx:
    image: nginx:1.16.1
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/${CSP_ENV}/localhost.conf:/etc/nginx/sites-enabled/localhost.conf
      - ./src/nimiq/conf/${NIMIQ_ENV}/wallet.conf:/etc/nginx/sites-enabled/wallet.conf
      - ./src/nimiq/conf/${NIMIQ_ENV}/hub.conf:/etc/nginx/sites-enabled/hub.conf
      - ./src/nimiq/conf/${NIMIQ_ENV}/keyguard.conf:/etc/nginx/sites-enabled/keyguard.conf
      - ./conf/mime.types:/etc/nginx/mime.types
      - ./src/sites:/usr/share/nginx/html
      - ./src/nimiq/sites/wallet:/usr/share/nginx/wallet
      - ./src/nimiq/sites/hub:/usr/share/nginx/hub
      - ./src/nimiq/sites/keyguard:/usr/share/nginx/keyguard
      - ./logs/error.log:/etc/nginx/error.log
      - ./src/tmp/favicon.ico:/usr/share/nginx/img/favicon.ico
    ports:
      - 8085:8085
      - 8000:8000
      - 8080:8080
      - 8081:8081

  app:
    container_name: manifest-con
    build: 
      context: .
      dockerfile: conf/manifest_docker_file
    volumes:
      - ./src/sites:/go/src/go-with-compose
      - ./src/keys:/keys
    working_dir: /go/src/go-with-compose
    tty: true
    stdin_open: true
