version: '3'
services:
  nginx:
    image: nginx:1.16.1
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/${CSP_ENV}/wallet.conf:/etc/nginx/sites-enabled/wallet.conf
      - ./conf/keyguard.conf:/etc/nginx/sites-enabled/keyguard.conf
      - ./conf/${CSP_ENV}/hub.conf:/etc/nginx/sites-enabled/hub.conf
      - ./conf/mime.types:/etc/nginx/mime.types
      - ./sites:/usr/share/nginx/html
      - ./conf/error.log:/etc/nginx/error.log
    ports:
      - 8000:8000
      - 8080:8080
      - 8081:8081
